image: node:latest

before_script:
  - node -v
  - npm -v

stages:
  - deploy

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master
